# Generated by Django 3.1.1 on 2020-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='winners/', verbose_name='Winner Image')),
            ],
            options={
                'verbose_name': 'Winner',
                'verbose_name_plural': 'Winners',
            },
        ),
        migrations.AlterField(
            model_name='option',
            name='choice',
            field=models.CharField(max_length=100, verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=20, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
