# Generated by Django 3.1.1 on 2020-12-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201207_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='choice',
            field=models.CharField(max_length=200, verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200, verbose_name='Answer'),
        ),
    ]
