# Generated by Django 3.1.1 on 2020-12-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201207_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='winners/', verbose_name='Winner Image'),
        ),
    ]
